pipeline {
    agent any
    environment {
        GOOGLE_PROJECT_ID = "Proyecto-ideas-extraordinarias" 
        GOOGLE_APPLICATION_CREDENTIALS = credentials('service-account-jenkins')
    }
    
    stages{
        
        stage('clean workspaces -------------------------------') { 
            steps {
              cleanWs()
              sh 'env'
            } //steps
        }  //stage

        
        stage("git clone --------------------------------------"){
            steps {
                cleanWs()
                    checkout([$class: 'GitSCM', 
                    branches: [[name: '*/master']], 
                    doGenerateSubmoduleConfigurations: false, 
                    extensions: [[$class: 'CleanCheckout']], 
                    submoduleCfg: [], 
                    userRemoteConfigs: [
                        [url: 'git@github.com:agustinjaume/jenkins-terraform.git', credentialsId: '']
                        ]])
                sh 'pwd' 
                sh 'ls -l'
            } //steps
        }  //stage
    
        stage('Terraform init---------------------------') {
         steps {
            sh 'terraform --version'
            sh 'env'
            sh 'pwd'
            sh ' cd bastion && ls -la'
            sh ' cd bastion && gcloud projects list'
            sh ' cd bastion && terraform init -var-file="../variables/dev.tfvars"'
            } //steps
        }  //stage

        stage('Terraform plan-------------------------') {
            steps {
               sh 'cd bastion && ls -la'
               sh 'cd bastion && gcloud projects list'
               sh 'cd bastion &&terraform plan -var-file="../variables/dev.tfvars" -out="../variables/terraform-dev.tfplan" -lock=false'
            } //steps
        }  //stage

        stage('Terraform apply--------------------') {
            steps {
               sh 'cd bastion && ls -la'
               sh 'cd bastion && terraform apply "../variables/terraform-dev.tfplan" -auto-approve -refresh=true'
            } //steps
        }  //stage
   }  // stages
} //pipeline