pipeline {
    agent any
    environment {
        GOOGLE_PROJECT_ID = "Proyecto-ideas-extraordinarias"  //${OAUTH_IT_PROJECT_ID}"
        GOOGLE_APPLICATION_CREDENTIALS = credentials('service-account-jenkins')
    }
    
    stages{
        
        stage('clean workspaces') { 
            steps {
              cleanWs()
              sh 'env'
            } //steps
        }  //stage

        
        stage("git clone"){
            steps {
                cleanWs()
                    checkout([$class: 'GitSCM', 
                    branches: [[name: '*/master']], 
                    doGenerateSubmoduleConfigurations: false, 
                    extensions: [[$class: 'CleanCheckout']], 
                    submoduleCfg: [], 
                    userRemoteConfigs: [
                        [url: 'git@github.com:agustinjaume/jenkins-terraform.git', credentialsId: '']
                        ]])
                sh 'pwd' 
                sh 'ls -l'
            } //steps
        }  //stage
    


        stage('Terraform init') {
         steps {
         sh 'terraform --version'
         sh  'env'
         sh 'pwd'
         sh ' cd bastion && gcloud projects list'
         sh ' cd bastion && terraform init'
         sh ' cd bastion && ls -la'
            } //steps
        }  //stage
   }
}